[meta]
name        = "Stat Exporter"
author      = "risyn_1"
category    = "Utility"
version     = "1.1.0"

[script]
#__DEFINES__
dependencies = ["ManiaExchange", "GrindingStats"]
optional_dependencies = ["ChampionMedals", "WarriorMedals"]